export const paths = {
    // paths
    aboutUs: 'about-us',
    accountSettings: 'account-settings',
    careers: 'careers',
    contactUs: 'contact-us',
    cookies: 'cookies',
    createAccount: 'create-account',
    home: '',
    login: 'login',
    massicot: 'massicot',
    minium: 'minium',
    news: 'news',
    notFound: '**',
    ocher: 'ocher',
    orpiment: 'orpiment',
    ourStory: 'our-story',
    privacy: 'privacy',
    shop: 'shop',
    sinopia: 'sinopia',
    support: 'support',
    terms: 'terms',
    theTeam: 'the-team',

    // title
    aboutUsData: 'About Us',
    accountSettingsData: 'Account Settings',
    careersData: 'Careers',
    contactUsData: 'Contact Us',
    cookiesData: 'Cookies',
    createAccountData: 'Create an Account',
    homeData: 'Welcome',
    loginData: 'Login',
    massicotData: 'Massicot',
    miniumData: 'Minium',
    newsData: 'News',
    notFoundData: 'Oh Nooes',
    ocherData: 'Ocher',
    orpimentData: 'Orpiment',
    ourStoryData: 'Our Story',
    privacyData: 'Privacy',
    shopData: 'Shop',
    sinopiaData: 'Sinopia',
    supportData: 'Support',
    termsData: 'Terms',
    theTeamData: 'The Team',
}
